# These are supported funding model platforms

github: [firasdib]
#patreon: # Replace with sicadigiacomo username
#open_collective: # Replace with a single Open Collective sicadigiacomo username
#ko_fi: # Replace with a single sicadigiacomo username
#tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
#community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
#bitpay: # Replace with a single sicadigiacomo  username
#issuehunt: # Replace with a single sicadigiacomo username
#otechie: # Replace with a single sicadigiacomo username
#custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
bc1qazxmpmxlczpn636cl8j33xmtmx4jkvpae0pj8p
